# Generated by Django 5.0.3 on 2024-09-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('born', models.DateField()),
                ('birthplace', models.CharField(max_length=255)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('gen', models.IntegerField()),
            ],
        ),
    ]
