# Generated by Django 5.0.3 on 2024-09-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CGM48FANS', '0003_alter_songinformation_sembatsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinformation',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CGM48FANS.member2'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
